version: '3'
services:
  prometheus:
    image: prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "9000:9000"
    depends_on:
      - prometheus
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - prometheus